### ISSUE TITLE
Could not find template view file: "index".

### ISSUE THREAD

**Issue by mandahylla** [arif-rh/ci4-themes#1]
i got this error when i'm trying to use theme : : render
![Capture tatter themes](https://github.com/arif-rh/ci4-themes/assets/321008/4f730b83-8239-4fc0-900b-17b6cd0b85ea)
here is my homeController
![Capture arifh themes2](https://github.com/arif-rh/ci4-themes/assets/321008/4af0fa45-ed04-426b-bacd-dc36a084ca43)

Is there anything i've not do ? 
I specify that i begin with this.

**Comment by arif-rh** [comment]
I am really sorry. I have not actively maintain this library.

But as error said, it seem you do not have `index.php` template in your theme folder.

And please also consider that this library has not been update for more than a year, so this library maybe will not be compatible with the latest CodeIgniter version, since has not been tested to the latest version.
